from setuptools import setup

setup(
    name="open-agent-cli",
    version="2.2.0",
    py_modules=[
        "loop",
        "memory",
        "mission",
        "out_of_the_box",
        "web_search",
        "youtube_utils",
        "providers",
        "webui",
        "mcp_client",
    ],
    packages=["job_search"],
    python_requires=">=3.10",
    install_requires=[
        "httpx",
        "prompt_toolkit",
        "watchdog",
        "beautifulsoup4",
        "pygments",
        "youtube-transcript-api",
        "yt-dlp",
        "playwright",
        "pyee",
        "greenlet",
    ],
    entry_points={
        "console_scripts": [
            "openagent=loop:main",
            "op=loop:main",
        ],
    },
    author="Open-Agent Contributors",
    description="A local-first, privacy-focused terminal IDE agent with persistent memory and mission tracking.",
    long_description=open("README.md", encoding="utf-8").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/oppenheimer-rick/open-agent",
    license="MIT",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Environment :: Console",
        "Intended Audience :: Developers",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Programming Language :: Python :: 3.13",
        "Topic :: Software Development",
        "Topic :: Terminals",
    ],
)
